import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
     expediente: false,
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  // Administrador Modules
  {
    path: '/admin/dashboard',
    title: 'Buscar Expediente',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'find_in_page',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },

  {
    path: '/Administrador/Administrador-materiales',
    title: 'Herramientas',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'construction',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },
  {
    path: '/Administrador/Administrador-centros',
    title: 'Transferencias',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'drive_file_move',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },
  {
    path: '/Administrador/Administrador-solicitudes',
    title: 'Reportes',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'table_chart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },
  {
    path: '/Administrador/Administrador-solicitudes',
    title: 'Consulta',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'find_replace',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },


  {
    path: '/administrador/generales',
    title: 'Generales',
    iconType: 'material-icons-two-tone',
    expediente: true,
    icon: 'dvr',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },

  {
    path: '/administrador/anexos',
    title: 'Anexos',
    iconType: 'material-icons-two-tone',
    expediente: true,
    icon: 'account_balance_wallet',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },

  {
    path: '/administrador/garantias',
    title: 'Garantías',
    iconType: 'material-icons-two-tone',
    expediente: true,
    icon: 'attach_money',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },
  {
    path: '/administrador/multas',
    title: 'Multas',
    iconType: 'material-icons-two-tone',
    expediente: true,
    icon: 'gavel',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },



  {
    path: '/administrador/transferir',
    title: 'Transferir',
    iconType: 'material-icons-two-tone',
    expediente: true,
    icon: 'drive_file_move',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },




  {
    path: '/administrador/recibirtransfer',
    title: 'Recibir Transferencia',
    iconType: 'material-icons-two-tone',
    expediente: true,
    icon: 'drive_file_move_rtl',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [],
  },


  
  {
    path: '',
    title: 'Reportes',
    iconType: 'material-icons-two-tone',
    expediente: true,
    icon: 'summarize',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Administrador'],
    submenu: [      
      {   path: '/admin/reportes/reporteador',
          title: 'Reporteador',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          expediente:true,
          badgeClass: '',
          role: [''],
          submenu: [],
    }],
  },










  // Almacenista Modules

  {
    path: '/almacenista/dashboard',
    title: 'Panel',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Almacenista'],
    submenu: [],
  },
   {
    path: '/almacenista/Administrador-sol',
    title: 'Surtir',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'view_list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Almacenista'],
    submenu: [],
  },

  // Coordinador Modules

  {
    path: '/coordinador/dashboard',
    title: 'Panel',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Coordinador'],
    submenu: [],
  },
  {
    path: '/coordinador/solicitudes',
    title: 'Mis Solicitudes',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Coordinador'],
    submenu: [],
  }, 
   {
    path: '/coordinador/Administrador-sol',
    title: 'Administradoristrar',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'view_list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Coordinador'],
    submenu: [],
  },
  {
   path: '/coordinador/sol-hist',
   title: 'Historico',
   iconType: 'fas fa-history fa-lg',
   expediente:false,
   icon: '',
   class: '',
   groupTitle: false,
   badge: '',
   badgeClass: '',
   role: ['Coordinador'],
   submenu: [],
 },
  {
    path: '/coordinador/Administrador-per',
    title: 'Periodos',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'date_range',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Coordinador'],
    submenu: [],
  },

  // solicitante Modules

  {
    path: '/solicitante/dashboard',
    title: 'Panel',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Solicitante'],
    submenu: [],
  },
  {
    path: '/solicitante/solicitudes',
    title: 'Mis Solicitudes',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Solicitante'],
    submenu: [],
  },

  
  // Capturista Modules

  {
    path: '/capturista/dashboard',
    title: 'Panel',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Capturista'],
    submenu: [],
  },
  {
    path: '/capturista/solicitudes',
    title: 'Mis Solicitudes',
    iconType: 'material-icons-two-tone',
     expediente: false,
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Capturista'],
    submenu: [],
  },

  // Common Module


];
